### ISSUE TITLE
Error libadalang when use populate_lexical_env

### ISSUE THREAD

**Issue by AntoMartin** [AdaCore/libadalang#10] opened 2017-04-28 09:34 UTC
Hello,

We tried to use libadalang to generate lexical environnement but when we run it, populate_lexical_env crashes for 2 on 4 test files (types_bidon.ads which defines external types and test-startup.adb which is a separate of test.adb).

Here are the files: test files, executable and the way to run it.
[parsing_test.zip](https://github.com/AdaCore/libadalang/files/963971/parsing_test.zip)

Do you have any idea of the source of the problem?

Regards,

**Comment by pmderodat** [comment] 2017-04-28 09:52
Hello @AntoMartin,

First of all, please note that semantic analysis in Libadalang (hence `populate_lexical_env`) is still under heavy development, so it’s very likely in the future that you will come into either a bug or a not-yet-implemented feature. :-)

In this specific instance (thank you for the reproducer), the problem is that you are not using the API the way you are supposed to. Sorry if this is unclear right now, but AnalysisUnit’s constructor is not meant to be directly called: one should instead create an AnalysisContext first, and then use its methods to create units. Try the following instead:

```python
ctx = lal.AnalysisContext()
for f in file_list:
    print(f)
    unit = ctx.get_from_file(f)
    unit.populate_lexical_env()
```

If you want to know more about how the Python API should be used, have a look at the testsuite: for instance <https://github.com/AdaCore/libadalang/blob/master/ada/testsuite/python_support/symbol_resolution_driver.py>. But again, please keep in mind that the semantic resolution part of it is still being worked out and it’s likely that it will change in the (near?) future.

In the meantime, I’ll try to enhance/add docstrings to make it explicit when constructors are for internal use only.

Regards,

**Comment by pmderodat** [comment] 2017-04-28 10:29
I’ve just pushed some changes in Langkit to make it explicit that AnalysisUnit (and some other classes) are not meant to be instantiated directly. Assuming that your issues is solved, I’m now closing this ticket. Thank you again for your report!

**Closed by pmderodat** 2017-04-28 10:29 UTC
