### ISSUE TITLE
Name resolution: Bug with subtype declarations

### ISSUE THREAD

**Issue by Roldak** [AdaCore/libadalang#48] opened 2017-12-19 10:06 UTC
```Ada
procedure Test is
   subtype Natural is Integer range 0 .. Integer'Last;
   x : Integer := Natural'First;
begin
   null;
end Test;
```

Getting a `libadalang.PropertyError: raised LIBADALANG.ANALYSIS.PROPERTY_ERROR : dereferencing a null access` error when trying to get property `p_expression_type` on the literal `0` appearing in the subtype declaration.

**Comment by raph-amiard** [comment] 2017-12-19 16:33
Duplicate of #46 I think

**Comment by raph-amiard** [comment] 2017-12-20 09:46
Fixed

**Closed by raph-amiard** 2017-12-20 09:46 UTC
Labels: name resolution
