### ISSUE TITLE
Clarification on licensing

### ISSUE THREAD

**Issue by andrewvaughanj** [AdaCore/libadalang#284] opened 2019-06-30 21:33 UTC
Hi,

I am trying to understand the licensing of `libadalang`, with respect to its use of "GCC Runtime Library Exception". It is my understanding that the runtime exception "kicks in" when `gcc` links something in as part of its compilation process (and that's _only_ when the linking exception applies):

For example, [GCC Runtime Library Exception Rationale and FAQ](https://www.gnu.org/licenses/gcc-exception-3.1-faq.en.html):

> Compilation Process starts when you feed any high-level code to GCC, and ends as soon as it generates anything that can be considered Target Code.

and equally from `libadalang`'s [COPYING.RUNTIME](https://github.com/AdaCore/libadalang/blob/master/COPYING.RUNTIME):

> provided that all Target Code was generated by Eligible Compilation Processes

However, my confusion here stems from two parts:

- I am not aware that `libadalang` is used/included in FSF GNAT

- Even if `libadalang` _was_ used in FSF GNAT, I cannot understand why any compilation would include parts of libadalang _in the final executable_ (e.g., like with `libgcc`)

This means I am quite confused why the main license on the GitHub repo is specified as "GCC Runtime Library Exception". Additionally, when you refer to `libadalang`'s [README.md](https://github.com/AdaCore/libadalang/blob/master/README.md), there's no discussion on licensing either.

I think the intent of `libadalang`'s license is to say "this library is GPLv3" (not **LGPL**v3, although this would be preferable, imo). However, I think having the "default license" listed on GitHub.com as "GCC Runtime Library Exception" is quite confusing.

Would it be possible to provide some clarification on this?

Cheers,

Andrew

**Comment by raph-amiard** [comment] 2019-09-21 21:38
Hi Andrew. I can see why this would be confusing, but am not qualified to give more insights into this. I just know it's the licence we use for all our libraries. Will ask somebody more knowledgeable at AdaCore.

**Comment by andrewvaughanj** [comment] 2020-06-16 21:10
Today (June 16th, 2020), @yakobowski gave a presentation on the work he's done at AdaCore about integrating `libadalang` into the MIT-licensed static analysis tool [`infer`](https://github.com/facebook/infer).

I raised a query about under what license the resulting binary would be (given that `libadalang` is GPL and `infer` is MIT), and here is @yakobowski's response: 

<img width="381" alt="Screenshot 2020-06-16 at 21 59 47" src="https://user-images.githubusercontent.com/14277540/84827704-c641df00-b01c-11ea-9372-bdf1a087bd28.png">

To quote what was said on Slack:

Boris Yakobowski:

> Ok, so we have clarified things. Infer is actually not linked against
> LibAdaLang at all. LAL is loaded at execution time through libdl. In that
> case, the library exception explicitly allows dynamic linking free from
> gpl contamination. Infer is decoupled from the LAL license.
> 

Andrew V. Jones (me):

> Wait, sorry, are you saying it gets dlopen’d?
> 

(to which Boris replied with a 👍)

## Question

I'm not taking what Boris Yakobowski wrote as an official statement from AdaCore (I'm not saying it _isn't_, I'm just not saying it _is_), but what is AdaCore's perspective here? Are AdaCore happy that programs that `dlopen` `libadalang` are _not_ bound by the GPL?

Some of the [examples](https://github.com/AdaCore/libadalang/tree/master/ada/testsuite/tests/python) that come with `libadalang` are written in Python, and therefore all of these will be loading `libadalang` via a `dlopen` (via Python), so the extension here would be that writing a Python program that interacts with `libadalang` is not bound by the GPL.

I would really appreciate some clarification here.

**Comment by raph-amiard** [comment] 2020-06-17 13:56
Hi @andrewvaughanj, thanks for your patience, and bringing back that important issue. Just so you know it's acknowledged and we're working on it :slightly_smiling_face:

**Comment by raph-amiard** [comment] 2020-06-18 15:06
Hi again @andrewvaughanj!

From a technical perspective, you can "combine" Libadalang with your
work in two different ways, both of which are addressed by the
exception:

1.) You're statically linking the Libadalang library into your Ada
analysis application utilizing the Ada interface of Libadalang.

2.) You're using one of the other bindings to Libadalang (Python,
OCaml). In this case, you're using the ctypes interface, which relies
on dynamic linking: the Libadalang tools are built into a dynamic
library and accessed dynamically via that other language's runtime.

There may be some confusion surrounding the purpose of the "GCC
Runtime Library Exception".  As the title suggests, it was intended to
apply to the GCC *Runtime*, not GCC itself.  Its purpose was to allow
the GCC Runtime Library to be used with software that had non-FLOSS
licenses.  Many other libraries, such as Libadalang, have adopted the
same license for their libraries for the same purpose.  In other words,
the name is historical based on who first used it and is not meant to
imply that it has anything to do with GCC.

For further clarity on the interpretation of the GPL and GPL Runtime
Exception licenses, we refer you to the current maintainers of those
documents at the FSF. In fact, for items copyrighted by AdaCore, we
defer the interpretation of these licenses to the FSF as well.

You might find pertinent information and contact information for the
Compliance Lab at the FSF at the following resources:

https://www.gnu.org/licenses/gpl-faq.en.html
https://www.gnu.org/licenses/gcc-exception-3.1-faq.html

**Closed by raph-amiard** 2020-06-18 15:06 UTC
Labels: question
