### ISSUE TITLE
utf-8 analysis context not working

### ISSUE THREAD

**Issue by jotd666** [AdaCore/libadalang#7] opened 2017-02-22 22:24 UTC
I set it up like in the examples, but when I open a file with degrees (°) even in comments, libadalang refuses to analyze it.

If I remove this char, it works properly (not an issue at this point, I can workaround)

BTW in case you did not get it I'm JF Fabre from Thales Avionics and I'm more than pleased with libadalang at this point.

**Comment by pmderodat** [comment] 2017-02-23 08:50
Hello Jean-François :-)

We are glad to ear you enjoy using Libadalang! Regarding the issue you are reporting, this is very surprising to us, as we have several testcases that are supposed to demonstrate that analyzing units with non-default encodings, for instance using the Python API: <https://github.com/AdaCore/libadalang/tree/master/ada/testsuite/tests/python/unicode/valid_input>. We run these testcases daily and don’t have known issues with Unicode support.

Can you please give us way to reproduce the error you are describing so we can have a look?

Thank you in advance,

**Comment by raph-amiard** [comment] 2017-11-12 16:10
Hello Jean-François !

Hope you're still satisfied with LAL at this point ! We'll have some updates regarding name resolution very soon hopefully :)

Concerning this issue, I'll close it since we did not get any feedback from you. Feel free to reopen if needed !

**Closed by raph-amiard** 2017-11-12 16:10 UTC
