### ISSUE TITLE
having source files in different subdirectories causes property errors (null access) that don't happen if all in same directory.

### ISSUE THREAD

**Issue by forsyth** [AdaCore/libadalang#862] opened 2021-11-04 11:07 UTC
This is for libadalang commit 1428b3f723859e09151404b0338d1935e548a496

I've attached a file fails.tar.gz
[fails.tar.gz](https://github.com/AdaCore/libadalang/files/7474301/fails.tar.gz)
 containing a directory "fails" with two subdirectories, fail1a and fail1b. Both have the same 3 input files: systemtypes.ads, test_pkg.ads and test_pkg.adb, and a libadalang test program main.adb. The difference is that fail1a has systemtypes.ads and the test_pkg.ad[sb] in different subdirectories.

In both fail1a and fail1b the test program main.adb loads 3 analysis units. They are loaded from explicit file names using Get_From_File. The only difference between the main programs is in those 3 lines. The task is to find all the Defining_Names in all 3 units and apply P_Unique_Identifying_Name. When that works, the Text for the node is printed.
At the start, all three units are printed by unit.Root.Print, to show that in both cases the units are successfully read and parsed.
They have no Diagnostics.
Optionally, Populate_Lexical_Env is applied to each unit, but I found it made no difference to the results.

Fail1b works as expected: every defining name is found in all three units in turn, and P_Unique_Identifying_Name is applied successfully. (I know it's called fail1b but that one works as expected.)

Fail1a successfully loads and prints the trees, and finds all the defining names in the first unit and gets their unique names. On the second unit, test_pkg.ads, it works for the defining name in the package spec, but not for the subprogram spec immediately within. It finds Code_To_State as a defining name, but applying the P_Unique_Identifying_Name function gives
```
   |  Id[4:13-4:26]: Code_To_State

raised LANGKIT_SUPPORT.ERRORS.PROPERTY_ERROR : dereferencing a null access
```
It isn't restricted to P_Unique_Identifying_Name. That's just how I first noticed it. It affects P_Next_Part and many other fundamental ones the same way. In one traceback I found it ended up raising that exception at:
```
  --# expr-start 9271 '<FieldAccess .designated_type>' Fld /home/stomlinson/rvs/libadalang/libadalang/ada/ast.py:7179
  Fld := Libadalang.Implementation.Dispatcher_Type_Expr_P_Designated_Type (Node => Ent.Node, Origin => Bound_Origin, 
  E_Info => Ent.Info);
        if Fld.Node = null then
           raise Property_Error with "dereferencing a null access";
        end if;
```
which looked as though despite having the units to hand and parsed (it could display them) it hadn't successfully done name resolution etc on the second and third. The only difference seems to be where the source files live.

**Comment by Roldak** [comment] 2022-02-07 15:27
Hello,

After looking at your reproducer, I think this is because you are calling `Create_Context` without a unit provider, meaning the default unit provider is used which only looks for files in the current directory. Instead, you should create your `Analysis_Context` by specifying a gpr file: see https://docs.adacore.com/live/wave/libadalang/html/libadalang_ug/ada_api_tutorial.html#resolving-files for more details.

Best regards,

Romain

**Closed by Roldak** 2022-02-07 15:27 UTC
